Alias /api /var/www/html/backend/api
Alias /uploads /var/www/html/backend/uploads

<Directory /var/www/html/backend/api>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

<Directory /var/www/html/backend/uploads>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
